In [4]:
# Importing the libraries 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as pyplot 
import seaborn as sns
%matplotlib inline

# Ignore harmless warnings 

import warnings 
warnings.filterwarnings("ignore")

# Set to display all the columns in dataset

pd.set_option("display.max_columns", None)

# Import psql to run queries 

import pandasql as psql

# import datetime class from datetime module

from datetime import datetime

In [5]:
# Load the Auto insurance data

autodata = pd.read_csv(r"C:\Users\Admin\Downloads\Raju Sir DLS\Auto_Quote_Data_V2.0.csv", header=0) 

# Copy the file to back-up

autodata_bk = autodata.copy()

# Display first five records

autodata.head()

,Quote_Num,Agent_Type,Q_Creation_DT,Q_Valid_DT,Policy_Bind_DT,Region,Agent_Num,Policy_Type,HH_Vehicles,HH_Drivers,Driver_Age,Driving_Exp,Prev_Accidents,Prev_Citations,Gender,Marital_Status,Education,Sal_Range1,Sal_Range2,Coverage,Veh_Usage,Annual_Miles_Range,Vehicl_Cost_Range1,Vehicl_Cost_Range2,Re_Quote,Quoted_Premium,Policy_Bind
0,AQ-C-139212,EA,2020/04/25,2020/06/23,2020/05/23,C,2156,Car,3,3,43,26,0,0,Female,Widow,High School,> $ 25 K <= $ 40 K,> 25 K <= 40 K,Balanced,Commute,> 55 K,> $ 10 K <= $ 20 K,> 10 K <= 20 K,No,693.86,Yes
1,AQ-F-136117,EA,2020/02/21,2020/04/20,NaN,F,2153,Van,2,2,30,13,0,0,Female,Dirvorced,Ph.D,> $ 40 K <= $ 60 K,> 40 K <= 60 K,Balanced,Pleasure,> 7.5 K & <= 15 K,<= $ 10 K,<= 10 K,No,635.96,No
2,AQ-F-126801,EA,2020/06/19,2020/08/17,2020/07/12,F,2056,Truck,2,1,25,8,0,0,Female,Dirvorced,Ph.D,> $ 40 K <= $ 60 K,> 40 K <= 60 K,Basic,Commute,> 35 K & <= 45 K,> $ 10 K <= $ 20 K,> 10 K <= 20 K,No,780.64,Yes
3,AQ-E-143467,EA,2020/05/02,2020/06/30,2020/05/24,E,2138,Car,1,2,43,26,0,0,Female,Married,Ph.D,> $ 90 K,> 90 K,Basic,Pleasure,<= 7.5 K,<= $ 10 K,<= 10 K,No,723.15,Yes
4,AQ-C-143827,EA,2020/02/12,2020/04/11,2020/02/25,C,2327,Truck,3,1,40,23,0,0,Female,Widow,High School,<= $ 25 K,<= 25 K,Basic,Pleasure,> 35 K & <= 45 K,<= $ 10 K,<= 10 K,No,738.14,Yes

In [6]:
# Displaying the dataset information

autodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146259 entries, 0 to 146258
Data columns (total 27 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Quote_Num           146259 non-null  object
 1   Agent_Type          146259 non-null  object
 2   Q_Creation_DT       146259 non-null  object
 3   Q_Valid_DT          146259 non-null  object
 4   Policy_Bind_DT      32502 non-null   object
 5   Region              146259 non-null  object
 6   Agent_Num           146259 non-null  int64
 7   Policy_Type         146259 non-null  object
 8   HH_Vehicles         146259 non-null  int64
 9   HH_Drivers          146259 non-null  int64
 10  Driver_Age          146259 non-null  int64
 11  Driving_Exp         146259 non-null  int64
 12  Prev_Accidents      146259 non-null  int64
 13  Prev_Citations      146259 non-null  int64
 14  Gender              146259 non-null  object
 15  Marital_Status      146259 non-null  object
 16  Education           146259 non-null  object
 17  Sal_Range1          146259 non-null  object
 18  Sal_Range2          146259 non-null  object
 19  Coverage            146259 non-null  object
 20  Veh_Usage           146259 non-null  object
 21  Annual_Miles_Range  146259 non-null  object
 22  Vehicl_Cost_Range1  146259 non-null  object
 23  Vehicl_Cost_Range2  146259 non-null  object
 24  Re_Quote            146259 non-null  object
 25  Quoted_Premium      146259 non-null  float64
 26  Policy_Bind         146259 non-null  object
dtypes: float64(1), int64(7), object(19)
memory usage: 30.1+ MB

In [7]:
autodata = autodata.drop(['Quote_Num', 'Q_Valid_DT', 'Policy_Bind_DT'], axis=1)

In [8]:
autodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146259 entries, 0 to 146258
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Agent_Type          146259 non-null  object
 1   Q_Creation_DT       146259 non-null  object
 2   Region              146259 non-null  object
 3   Agent_Num           146259 non-null  int64
 4   Policy_Type         146259 non-null  object
 5   HH_Vehicles         146259 non-null  int64
 6   HH_Drivers          146259 non-null  int64
 7   Driver_Age          146259 non-null  int64
 8   Driving_Exp         146259 non-null  int64
 9   Prev_Accidents      146259 non-null  int64
 10  Prev_Citations      146259 non-null  int64
 11  Gender              146259 non-null  object
 12  Marital_Status      146259 non-null  object
 13  Education           146259 non-null  object
 14  Sal_Range1          146259 non-null  object
 15  Sal_Range2          146259 non-null  object
 16  Coverage            146259 non-null  object
 17  Veh_Usage           146259 non-null  object
 18  Annual_Miles_Range  146259 non-null  object
 19  Vehicl_Cost_Range1  146259 non-null  object
 20  Vehicl_Cost_Range2  146259 non-null  object
 21  Re_Quote            146259 non-null  object
 22  Quoted_Premium      146259 non-null  float64
 23  Policy_Bind         146259 non-null  object
dtypes: float64(1), int64(7), object(16)
memory usage: 26.8+ MB

In [21]:

autodata['Agent_Type'].value_counts()

Series([], Name: Agent_Type, dtype: int64)